const DataMedicine = [
    {
        "id": 1,
        "category":"Arthritis",
        "medicine":[
            {
                "img":"",
                "name":"Advil"
            },
            {
                "img":"",
                "name":"Arava"
            },
            {
                "img":"",
                "name":"Celecoxib"
            },
            {
                "img":"",
                "name":"Hydroxychloroquine"
            },
            {
                "img":"",
                "name":"Leflunomide"
            },
            {
                "img":"",
                "name":"Medrol"
            },
            {
                "img":"",
                "name":"Methotrexate"
            },
            {
                "img":"",
                "name":"Naproxen"
            },
            {
                "img":"",
                "name":"Pennsaid"
            },
            {
                "img":"",
                "name":"Prednisone"
            },
            {
                "img":"",
                "name":"Remicade"
            },
            {
                "img":"",
                "name":"Rituximab"
            },
            {
                "img":"",
                "name":"Sulfasalazine"
            },
            {
                "img":"",
                "name":"Tocilizumab"
            },
            {
                "img":"",
                "name":"Tylenol"
            },
            {
                "img":"",
                "name":"Voltaren Gel"
            }
        ]
    },
    {
        "id": 2,
        "category":"Asthma",
        "medicine":[
            {
                "img":"",
                "name":"Accolate"
            },
            {
                "img":"",
                "name":"Advair"
            },
            {
                "img":"",
                "name":"Atrovent"
            },
            {
                "img":"",
                "name":"Dupixent"
            },
            {
                "img":"",
                "name":"Fluticasone"
            },
            {
                "img":"",
                "name":"Formoterol"
            },
            {
                "img":"",
                "name":"Intal"
            },
            {
                "img":"",
                "name":"Nucala"
            },
            {
                "img":"",
                "name":"ProAir"
            },
            {
                "img":"",
                "name":"Proventil"
            },
            {
                "img":"",
                "name":"Pulmicort"
            },
            {
                "img":"",
                "name":"Qvar"
            },
            {
                "img":"",
                "name":"Serevent"
            },
            {
                "img":"",
                "name":"Singulair"
            },
            {
                "img":"",
                "name":"Symbicort"
            },
            {
                "img":"",
                "name":"Theo-24"
            },
            {
                "img":"",
                "name":"Ventolin"
            },
            {
                "img":"",
                "name":"Xolair"
            },
            {
                "img":"",
                "name":"Xopenex"
            }
        ]
    },
    {
        "id": 3,
        "category":"Conjunctivitis Eye",
        "medicine":[
            {
                "img":"",
                "name":"Alaway"
            },
            {
                "img":"",
                "name":"Alocril"
            },
            {
                "img":"",
                "name":"Alomide"
            },
            {
                "img":"",
                "name":"Alrex"
            },
            {
                "img":"",
                "name":"AzaSite"
            },
            {
                "img":"",
                "name":"Ciloxan"
            },
            {
                "img":"",
                "name":"Cromolyn sodium"
            },
            {
                "img":"",
                "name":"Erythromycin ophthalmic"
            },
            {
                "img":"",
                "name":"Naphcon-A,"
            },
            {
                "img":"",
                "name":"Ocuflox"
            },
            {
                "img":"",
                "name":"Opcon-A"
            },
            {
                "img":"",
                "name":"Pataday"
            },
            {
                "img":"",
                "name":"Patanol"
            },
            {
                "img":"",
                "name":"Pazeo"
            },
            {
                "img":"",
                "name":"Polytrim"
            },
            {
                "img":"",
                "name":"Pred Forte"
            },
            {
                "img":"",
                "name":"Refresh Tears"
            },
            {
                "img":"",
                "name":"Systane"
            },
            {
                "img":"",
                "name":"TheraTears"
            },
            {
                "img":"",
                "name":"Tobrex"
            },
            {
                "img":"",
                "name":"Visine-A"
            },
            {
                "img":"",
                "name":"Zaditor"
            }
        ]
    },
    {
        "id": 4,
        "category":"Covid-19",
        "medicine":[
            {
                "img":"",
                "name":"dexamethasone"
            },
            {
                "img":"",
                "name":"Heparin"
            },
            {
                "img":"",
                "name":"Molnupiravir"
            },
            {
                "img":"",
                "name":"Olumiant"
            },
            {
                "img":"",
                "name":"Paxlovid"
            },
            {
                "img":"",
                "name":"REGEN-COV"
            },
            {
                "img":"",
                "name":"Remdesivir"
            },
            {
                "img":"",
                "name":"sotrovimab"
            },
            {
                "img":"",
                "name":"Tocilizumab"
            }
        ]
    },
    {
        "id": 5,
        "category":"Diabetes",
        "medicine":[
            {
                "img":"",
                "name":"Acarbose"
            },
            {
                "img":"",
                "name":"Actos"
            },
            {
                "img":"",
                "name":"Amaryl"
            },
            {
                "img":"",
                "name":"Apidra"
            },
            {
                "img":"",
                "name":"Avandia"
            },
            {
                "img":"",
                "name":"Farxiga"
            },
            {
                "img":"",
                "name":"Glucotrol"
            },
            {
                "img":"",
                "name":"Glucovance"
            },
            {
                "img":"",
                "name":"Glyset"
            },
            {
                "img":"",
                "name":"Humalog"
            },
            {
                "img":"",
                "name":"Humulin N"
            },
            {
                "img":"",
                "name":"Humulin R"
            },
            {
                "img":"",
                "name":"Invokana"
            },
            {
                "img":"",
                "name":"Januvia"
            },
            {
                "img":"",
                "name":"Jardiance"
            },
            {
                "img":"",
                "name":"Lantus"
            },
            {
                "img":"",
                "name":"Metformin"
            },
            {
                "img":"",
                "name":"Nesina"
            },
            {
                "img":"",
                "name":"Novolin Rl"
            },
            {
                "img":"",
                "name":"NovoLog"
            },
            {
                "img":"",
                "name":"Prandin"
            },
            {
                "img":"",
                "name":"Starlix"
            },
            {
                "img":"",
                "name":"Tirzepatide"
            }
        ]
    },
    {
        "id": 6,
        "category":"Diarrhea",
        "medicine":[
            {
                "img":"",
                "name":"Azithromycin"
            },
            {
                "img":"",
                "name":"Bentyl"
            },
            {
                "img":"",
                "name":"Ciprofloxacin"
            },
            {
                "img":"",
                "name":"Diphenoxylate and Atropine"
            },
            {
                "img":"",
                "name":"Imodium"
            },
            {
                "img":"",
                "name":"Metronidazole"
            },
            {
                "img":"",
                "name":"Pedialyte"
            },
            {
                "img":"",
                "name":"Pepto-Bismol"
            },
            {
                "img":"",
                "name":"Xifaxan"
            }
        ]
    },
    {
        "id": 7,
        "category":"Drug Allergy",
        "medicine":[
            {
                "img":"",
                "name":"Acthar"
            },
            {
                "img":"",
                "name":"cetirizine"
            },
            {
                "img":"",
                "name":"hydroxyzine"
            },
            {
                "img":"",
                "name":"levocetirizine"
            },
            {
                "img":"",
                "name":"loratadine"
            },
            {
                "img":"",
                "name":"prednisone"
            },
            {
                "img":"",
                "name":"promethazine"
            },
            {
                "img":"",
                "name":"Vistaril"
            },
            {
                "img":"",
                "name":"Xyzal"
            },
            {
                "img":"",
                "name":"Zyrtec"
            }
        ]
    },
    {
        "id": 8,
        "category":"Flu",
        "medicine":[
            {
                "img":"",
                "name":"Advil"
            },
            {
                "img":"",
                "name":"Claritin"
            },
            {
                "img":"",
                "name":"Mucinex"
            },
            {
                "img":"",
                "name":"Oseltamivir"
            },
            {
                "img":"",
                "name":"Rapivab"
            },
            {
                "img":"",
                "name":"Robitussin DM"
            },
            {
                "img":"",
                "name":"Sudafed"
            },
            {
                "img":"",
                "name":"Tylenol"
            },
            {
                "img":"",
                "name":"Zanamivir-Relenza"
            }
        ]
    },
    {
        "id": 9,
        "category":"Gastritis",
        "medicine":[
            {
                "img":"",
                "name":"AcipHex"
            },
            {
                "img":"",
                "name":"Amoxicillin"
            },
            {
                "img":"",
                "name":"Biaxin"
            },
            {
                "img":"",
                "name":"Calcium Carbonate"
            },
            {
                "img":"",
                "name":"Flagyl"
            },
            {
                "img":"",
                "name":"Maalox"
            },
            {
                "img":"",
                "name":"Misoprostol"
            },
            {
                "img":"",
                "name":"Nexium"
            },
            {
                "img":"",
                "name":"Omeprazole"
            },
            {
                "img":"",
                "name":"Pepcid"
            },
            {
                "img":"",
                "name":"Prevacid"
            },
            {
                "img":"",
                "name":"Protonix"
            },
            {
                "img":"",
                "name":"Tagamet"
            },
            {
                "img":"",
                "name":"Zantac"
            }
        ]
    },
    {
        "id": 10,
        "category":"Hair Loss",
        "medicine":[
            {
                "img":"",
                "name":"Avodart"
            },
            {
                "img":"",
                "name":"Biotin"
            },
            {
                "img":"",
                "name":"Ketoconazole Shampoo"
            },
            {
                "img":"",
                "name":"Minoxidil"
            },
            {
                "img":"",
                "name":"Propecia"
            },
            {
                "img":"",
                "name":"Pumpkin Seed Oil"
            },
            {
                "img":"",
                "name":"Saw Palmetto"
            },
            {
                "img":"",
                "name":"Spironolactone"
            }
        ]
    },
    {
        "id": 11,
        "category":"Heart Disease",
        "medicine":[
            {
                "img":"",
                "name":"Accupril"
            },
            {
                "img":"",
                "name":"Aspirin"
            },
            {
                "img":"",
                "name":"Benicar HCT"
            },
            {
                "img":"",
                "name":"Caduet"
            },
            {
                "img":"",
                "name":"Capoten"
            },
            {
                "img":"",
                "name":"Coreg"
            },
            {
                "img":"",
                "name":"Cozaar"
            },
            {
                "img":"",
                "name":"digoxin"
            },
            {
                "img":"",
                "name":"Dilatrate-SR"
            },
            {
                "img":"",
                "name":"Diovan"
            },
            {
                "img":"",
                "name":"Effient"
            },
            {
                "img":"",
                "name":"enalapril"
            },
            {
                "img":"",
                "name":"Heparin_Sodium"
            },
            {
                "img":"",
                "name":"Hydralazine"
            },
            {
                "img":"",
                "name":"Imdur"
            },
            {
                "img":"",
                "name":"Inspra"
            },
            {
                "img":"",
                "name":"Lopressor"
            },
            {
                "img":"",
                "name":"Lotensin"
            },
            {
                "img":"",
                "name":"Lotrel"
            },
            {
                "img":"",
                "name":"Lovenox"
            },
            {
                "img":"",
                "name":"magnesium"
            },
            {
                "img":"",
                "name":"Monopril"
            },
            {
                "img":"",
                "name":"nifedipine"
            },
            {
                "img":"",
                "name":"Norvasc"
            },
            {
                "img":"",
                "name":"perindopril"
            },
            {
                "img":"",
                "name":"Plavix"
            },
            {
                "img":"",
                "name":"ramipril"
            },
            {
                "img":"",
                "name":"ticagrelor"
            },
            {
                "img":"",
                "name":"trandolapril"
            },
            {
                "img":"",
                "name":"Warfarin"
            },
            {
                "img":"",
                "name":"Zebetajpg"
            },
            {
                "img":"",
                "name":"Zestril"
            }
        ]
    },
    {
        "id": 12,
        "category":"Insect Bite",
        "medicine":[
            {
                "img":"",
                "name":"benzocaine"
            },
            {
                "img":"",
                "name":"Caladryl Clear"
            },
            {
                "img":"",
                "name":"Chiggerex"
            },
            {
                "img":"",
                "name":"pramoxine"
            }
        ]
    },
    {
        "id": 13,
        "category":"Sinusitis",
        "medicine":[
            {
                "img":"",
                "name":"amoxicillin.png"
            },
            {
                "img":"",
                "name":"Augmentin"
            },
            {
                "img":"",
                "name":"Azithromycin Dose Pack"
            },
            {
                "img":"",
                "name":"cefdinir"
            },
            {
                "img":"",
                "name":"Levaquin"
            },
            {
                "img":"",
                "name":"levofloxacin"
            },
            {
                "img":"",
                "name":"prednisone"
            },
            {
                "img":"",
                "name":"Zithromax"
            }
        ]
    },
]